name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  hardhat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          npm install
          npm run test
          npm run compile
        working-directory: ./hardhat
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          npm install
          npm run build
        working-directory: ./app
